name: adkf-jax
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.8
  - pip
  # Standard data science stuff
  - numpy
  - tqdm
  # ML libraries
  - jaxlib=*=*cuda*
  - jax
  - cuda-nvcc
  # Developer tools
  - pytest
  - pre-commit
  - coverage
  # Notebooks
  - jupyter
  - pip:
    - flax
    - optax
    - jaxopt
    - gpjax==0.5.9
